# Generated by Django 4.1.10 on 2023-10-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('UG', 'UG'), ('PHD', 'PHD'), ('PG', 'PG')], max_length=50, verbose_name='Course Type'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='college/image/', verbose_name='Image'),
        ),
    ]
