# Generated by Django 4.1.10 on 2023-11-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_alter_course_course_type_alter_faculty_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('PG', 'PG'), ('PHD', 'PHD'), ('UG', 'UG')], max_length=50, verbose_name='Course Type'),
        ),
    ]
