# Generated by Django 4.1.10 on 2023-11-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_alter_course_course_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='facultyID',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('UG', 'UG'), ('PHD', 'PHD'), ('PG', 'PG')], max_length=50, verbose_name='Course Type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('1', '1 Year'), ('2', '2 Year'), ('3', '3 Year'), ('4', '4 Year'), ('5', '5 Year'), ('6', '6 Year'), ('7', '7 Year'), ('8', '8 Year')], max_length=10, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sems',
            field=models.CharField(choices=[('1', '1 Sem'), ('2', '2 Sem'), ('3', '3 Sem'), ('4', '4 Sem'), ('5', '5 Sem'), ('6', '6 Sem'), ('7', '7 Sem'), ('8', '8 Sem'), ('9', '9 Sem'), ('10', '10 Sem'), ('11', '11 Sem'), ('12', '12 Sem'), ('13', '13 Sem'), ('14', '14 Sem'), ('15', '15 Sem'), ('16', '16 Sem')], max_length=10, verbose_name='Semisters'),
        ),
    ]
