# Generated by Django 4.1.10 on 2023-10-30 12:51

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.CharField(max_length=15, validators=[student.models.only_int], verbose_name='Phone Number'),
        ),
    ]
