# Generated by Django 4.1.10 on 2023-10-30 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('student', '0002_alter_student_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentCourse', to='college.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentDepartment', to='college.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollNo',
            field=models.CharField(default='0', max_length=15, verbose_name='Enrollment Number'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='student/image/', verbose_name='Image'),
        ),
    ]
