# Generated by Django 4.1.10 on 2023-10-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_course_student_department_student_enrollno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student/image/', verbose_name='Image'),
        ),
    ]
